FROM node:10.7-slim

ENV PORT 5000
EXPOSE $PORT

WORKDIR /app

# Make node modules cacheable
COPY ./yarn.lock ./package.json ./

# Install dependencies
RUN npm install -g yarn
RUN yarn install


# Copy code
COPY . .
RUN yarn build

# Start the server

CMD ["yarn", "webpack"]
