version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile_node
    volumes:
    - ./dist:/app/build
    working_dir: /app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    working_dir: /usr/share/nginx/html
