FROM node:10.7-slim

ENV PORT 5000
EXPOSE $PORT

WORKDIR /app

# Make node modules cacheable
COPY ./package.json ./

# Install dependencies
RUN yarn install --production=false


# Copy code
COPY . .

CMD ["yarn", "webpack"]
