#! /bin/bash -ex
cd $(dirname $0)/..

IMAGE_NAME=tiangou-react-app-build
CONTAINER_NAME=tiangou-react-app-build-container

docker build -f Dockerfile_node -t $IMAGE_NAME .

rm -rf ./dist
mkdir dist

docker run  --rm \
    -v "$(pwd)"/dist:/app/dist \
    -e NODE_ENV=production \
    --name $CONTAINER_NAME $IMAGE_NAME:latest
